# Generated by Django 3.1.3 on 2020-11-25 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogColegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Post', max_length=50, verbose_name='Título de la publicación')),
                ('portada', models.ImageField(null=True, upload_to='blog/portadas/', verbose_name='Portada de la publicación')),
                ('imagen_contenido', models.ImageField(null=True, upload_to='blog/imagenes-de-contenido/', verbose_name='Portada de la publicación')),
                ('youtube_link', models.CharField(max_length=255, null=True, verbose_name='Link de Youtube')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Autor de la publicación')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
            },
        ),
    ]
