# Generated by Django 3.1.3 on 2020-11-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_colegio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcolegio',
            name='portada',
            field=models.ImageField(upload_to='blog/portadas/', verbose_name='Portada de la publicación'),
        ),
    ]
