# Generated by Django 3.1.3 on 2020-11-25 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog_colegio', '0004_auto_20201125_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcolegio',
            name='fecha_publicacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de publicación'),
            preserve_default=False,
        ),
    ]
