# Generated by Django 3.1.3 on 2020-11-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_colegio', '0007_auto_20201125_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcolegio',
            name='contenido',
            field=models.TextField(default='Contenido', max_length=600, verbose_name='Contenido de la publicación'),
        ),
    ]
