# Generated by Django 3.1.3 on 2020-11-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_colegio', '0009_blogcolegio_contenido_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcolegio',
            name='contenido_add',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Contenido adicional para la publicación'),
        ),
    ]
