# Generated by Django 3.1.3 on 2020-11-24 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(limit_choices_to={'curso': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_web.curso')}, on_delete=django.db.models.deletion.CASCADE, to='portal_web.asignatura')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_web.curso')),
                ('estudiante', models.ManyToManyField(limit_choices_to={'curso': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_web.curso')}, to='portal_web.Estudiante')),
            ],
        ),
    ]
