# Generated by Django 3.1.3 on 2020-11-24 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Desrciba el compromiso que sus estudiantes tiene que hacer, trate de ser puntual para aminorarlas dudas de sus estudiantes.', max_length=500, verbose_name='Descripción o contenido'),
        ),
    ]
