# Generated by Django 3.1.1 on 2020-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='contacto',
            field=models.IntegerField(help_text='Ingrese el número de contacto de este docente', null=True, unique=True, verbose_name='Número telefónico de contacto'),
        ),
        migrations.AddField(
            model_name='docente',
            name='whatsapp',
            field=models.BooleanField(choices=[('True', 'WhatsApp disponible'), ('False', 'WhatsApp no disponible')], default='True', help_text='Indique si este docente tiene disponibilidad de ser conectado a través de WhatsApp', verbose_name='Disponibilidad para WhatsApp'),
        ),
    ]
