# Generated by Django 3.1.3 on 2020-11-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0002_auto_20201123_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estudiante',
            field=models.ManyToManyField(null=True, to='portal_web.Estudiante'),
        ),
    ]
