# Generated by Django 3.1.1 on 2020-11-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0002_auto_20201121_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='contacto',
            field=models.CharField(help_text='Ingrese el número de contacto de este docente', max_length=10, null=True, unique=True, verbose_name='Número telefónico de contacto'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='whatsapp',
            field=models.BooleanField(choices=[(True, 'WhatsApp disponible'), (False, 'WhatsApp no disponible')], default=True, help_text='Indique si este docente tiene disponibilidad de ser conectado a través de WhatsApp', verbose_name='Disponibilidad para WhatsApp'),
        ),
    ]
