# Generated by Django 3.1.3 on 2020-11-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0003_auto_20201123_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estudiante',
            field=models.ManyToManyField(help_text='Indique el o los estudiantes del curso que requieran hacer esta tarea.', to='portal_web.Estudiante', verbose_name='Estudiante(s)'),
        ),
    ]
