# Generated by Django 3.1.3 on 2020-11-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0004_auto_20201124_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='asignatura',
            field=models.ForeignKey(help_text='Es necesario también determinar a que asignatura está dirigida esta tarea (en caso de queusted dicte mas de una asignatura en un mismo curso).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_web.asignatura', verbose_name='Asignatura de la tarea'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='curso',
            field=models.ForeignKey(help_text='Especifique a que grupo de estudiantes de un grado determinado será esta tarea.', on_delete=django.db.models.deletion.CASCADE, to='portal_web.curso', verbose_name='Curso o grado'),
        ),
    ]
