# Generated by Django 3.1.3 on 2020-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0006_tarea_adjuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('DES', 'En desarrollo'), ('ENV', 'Enviada'), ('REA', 'Realizada'), ('CLF', 'Calificada')], default='DES', help_text='Estado de la tarea', max_length=3),
        ),
    ]
