# Generated by Django 3.1.3 on 2020-11-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0007_tarea_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('DES', 'En desarrollo'), ('ENV', 'Enviada'), ('REA', 'Realizada'), ('CLF', 'Calificada')], default='DES', max_length=3, verbose_name='Estado de la tarea'),
        ),
    ]
