# Generated by Django 3.1.3 on 2020-11-24 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0008_auto_20201124_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Desrciba el compromiso que sus estudiantes tiene que hacer, trate de ser puntual para aminorarlas dudas de sus estudiantes.', max_length=500, null=True, verbose_name='Descripción o contenido'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='titulo',
            field=models.CharField(blank=True, help_text='Asigne el título para esta tarea, sea lo mas específico posible para que los estudiantestengan claro el objetivo de la tarea.', max_length=100, null=True, verbose_name='Título de la tarea'),
        ),
    ]
