# Generated by Django 3.1.3 on 2020-11-24 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0011_auto_20201124_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'verbose_name': 'Tarea', 'verbose_name_plural': 'Tareas'},
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Asigne el título para el contenido desarrollado de esta clase', max_length=100, null=True, verbose_name='Título de la clase')),
                ('descripcion', models.TextField(help_text='Desrciba claramente el contenido de esta clase, puntualice lo que el estudiante encontrará en este tema, para luego complementarlo con los archivos adjuntos requeridos', max_length=500, null=True, verbose_name='Descripción o contenido')),
                ('adjuntos', models.FileField(help_text='Es recomendable dejar contenidos adjuntos como documentos, imagenes, etc para que el estudiantepueda instruirse sin inconvenientes.', null=True, upload_to='clases/', verbose_name='Archivos adjuntos')),
                ('asignatura', models.ForeignKey(help_text='Es necesario también determinar a que asignatura está dirigida esta clase (en caso de queusted dicte mas de una asignatura en un mismo curso).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal_web.asignatura', verbose_name='Asignatura de la tarea')),
                ('curso', models.ForeignKey(help_text='Especifique a que grupo de estudiantes de un grado determinado será esta clase.', on_delete=django.db.models.deletion.CASCADE, to='portal_web.curso', verbose_name='Curso o grado')),
                ('estudiante', models.ManyToManyField(help_text='Indique el o los estudiantes del curso que recibirán esta clase.', to='portal_web.Estudiante', verbose_name='Estudiante(s)')),
            ],
            options={
                'verbose_name': 'Clase',
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
