# Generated by Django 3.1.3 on 2020-11-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0014_clase_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='estado',
            field=models.BooleanField(choices=[(False, 'Clase inactiva'), (True, 'Clase activa')], default=False, verbose_name='Estado de la clase'),
        ),
    ]
