# Generated by Django 3.1.3 on 2020-11-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0015_auto_20201124_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='adjuntos',
            field=models.FileField(blank=True, help_text='Es recomendable dejar contenidos adjuntos como documentos, imagenes, etc para que el estudiantepueda instruirse sin inconvenientes.', null=True, upload_to='clases/', verbose_name='Archivos adjuntos'),
        ),
    ]
