# Generated by Django 3.1.3 on 2020-11-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0016_auto_20201124_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='whatsapp',
            field=models.CharField(help_text='Ingrese el número de contacto de este estudiante, también servirá para contacto por WhatsApp.\nNOTA: En caso de que el estudiante no posea este tipo de contacto agregar el del acudiente.', max_length=10, null=True, unique=True, verbose_name='Número telefónico de Whatsapp'),
        ),
    ]
