# Generated by Django 3.1.3 on 2020-11-24 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0017_estudiante_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='direccion',
            field=models.CharField(help_text='Indique la dirección de domicilio de este estudiante. En dado caso de que se requiera esta información para temas academicos con sus compañeros, docentes o administrativos de la institución.', max_length=255, null=True, verbose_name='Dirección de domicilio'),
        ),
    ]
