# Generated by Django 3.1.3 on 2020-11-25 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0019_auto_20201124_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('DES', 'En desarrollo'), ('ENV', 'Enviada y asignada'), ('REA', 'Realizada'), ('CLF', 'Calificada')], default='DES', max_length=3, verbose_name='Estado de la tarea'),
        ),
        migrations.CreateModel(
            name='SolucionTarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anotaciones', models.TextField(help_text='En este apartado irán las respuestas (si así se requieren) o comentarios adicionales respectoa la entrega de la tarea. Recuerde que la prioridad de solución de la tarea es por medio de archivos adjuntos.', max_length=500, null=True, verbose_name='Resolución o comentarios')),
                ('adjuntos', models.FileField(help_text='Es requerido subir la solución a la tarea por medio de un archivo adjunto.', upload_to='solucion_tareas/', verbose_name='Archivo adjunto de tarea')),
                ('estudiante', models.OneToOneField(help_text='Corresponde al usuario que desarrolla, desarrolló, o desarrollará la taréa correspondiente', on_delete=django.db.models.deletion.CASCADE, to='portal_web.estudiante', verbose_name='Estudiante que desarrolla la tarea')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal_web.tarea', verbose_name='Tarea Desarrollada')),
            ],
        ),
    ]
