# Generated by Django 3.1.3 on 2020-11-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_web', '0025_auto_20201125_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluciontarea',
            name='estado',
            field=models.CharField(choices=[('SINREV', 'Tarea sin revisar'), ('ENVIAD', 'Tarea enviada'), ('REVISD', 'Tarea calificada')], default='SINREV', max_length=6, verbose_name='Estado de resolución de la tarea'),
        ),
    ]
